name: Build & Release
on:
  # push events to main with tags matching semver
  push:
    branches: 
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package linux-x64
        run: |
          dotnet publish ./src --runtime linux-x64 --self-contained -p:PublishSingleFile=true -c Release -o ./out/linux-x64
          tar -czf ./out/prune-${{github.ref}}-linux-x64.tar.gz ./out/linux-x64
      - name: Package linux-arm64
        run: |
          dotnet publish ./src --runtime linux-arm64 --self-contained -p:PublishSingleFile=true -c Release -o ./out/linux-arm64
          tar -czf ./out/prune-${{github.ref}}-linux-arm64.tar.gz ./out/linux-arm64
      - name: Package win-x64
        run: |
          dotnet publish ./src --runtime win-x64 --self-contained -p:PublishSingleFile=true -c Release -o ./out/win-x64
          tar -czf ./out/prune-${{github.ref}}-win-x64.tar.gz ./out/win-x64